### ISSUE TITLE
Kolejne zadania na sprawdzian

### ISSUE THREAD

**Issue by bartlomiej-stefanski** [bartex00001/Szkolne-Zadania#3]
Zagadnienia do zrobienia

- [x] Dzielniki liczby
- [x] Rozkład na czynniki
- [x] Liczby doskonałe
- [x] Liczby skojarzone
- [x] Liczby zaprzyjaźnione
- [x] Zamiana liter
- [x] Fibbonacci
- [x] Kalkulator
- [x] Suma dwóch tablic
- [x] Rozwiąż równanie liniowe
- [x] Rozwiąż równanie kwadratowe

**Comment by PWok** [comment]
Wszystkie zagadnienia dodane
